name: Benchmark cloud remotes connection
on: [workflow_dispatch]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: System information
        run: sudo apt-get update -y;sudo apt-get install neofetch -y;neofetch

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Check rclone remotes connection
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/checkup_remotes.sh | bash

      - name: Run benchmark
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/benchmark_remotes.sh | bash

      - name: Cleanup remotes
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/cleanup_remotes.sh | bash

      - name: Showing Results
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/results.sh | bash
