name: Benchmark cloud remotes connection
on:
  workflow_dispatch:  # Manual trigger
  schedule:
    # Run at midnight (00:00) and every 4 hours (04:00, 08:00, 12:00, 16:00, 20:00)
    - cron: '0 0,4,8,12,16,20 * * *'
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: System information
        run: sudo apt-get update -y;sudo apt-get install neofetch -y;neofetch

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Check rclone remotes connection
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/checkup_remotes.sh | bash

      - name: Run benchmark
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/benchmark_remotes.sh | bash

      - name: Cleanup remotes
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/cleanup_remotes.sh | bash

      - name: Showing Results
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/results.sh | bash
