name: Benchmark cloud remotes connection
on: [workflow_dispatch]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Check rclone connection
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/check_remotes.sh | bash

      - name: Run benchmark
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/benchmark_remotes.sh | bash

      - name: Results
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/results.sh | bash
