# This is a basic workflow to help you get started with Actions

name: Run Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  FFMPEG_FLAGS: >-
    -threads 0
    -cpu-used 0
    -c:v libx264 -preset faster
    -x264-params "opencl=1:frame-threads=4"
    -vf "format=yuv420p,hwupload"
    -c:a aac -b:a 128k

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1
        
      - run: ffmpeg -i https://ahrimp4.rule34.xxx//images/2918/887553901a7d1cb6bdcf2bd3ddd6a850.mp4 -i https://rule34video.com/get_file/47/dfe7c09a9d1750cbe82d0c9f26e5a235fd48eda6ed/3610000/3610458/3610458_1080p.mp4/?download_filename=najar-aketa-mikoto-moans-no-x-ray_1080p.mp4&download=true&br=2284 -c:v copy -map 0:v:0 -map 1:a:0 -shortest output.mp4
      #- name: Setup Rclone
        #uses: AnimMouse/setup-rclone@v1
        #with:
          #rclone_config: ${{ secrets.RCLONE_CONFIG }}
          #disable_base64: true
        
      #- run: "rclone lsd gdrive:"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.*
