# This is a basic workflow to help you get started with Actions

name: Run Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  output_folder: ffmpeg-output

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- uses: actions/checkout@v4
      
      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1
        
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Check rclone connection
        run: curl -fssL https://github.com/yaudahj/github-actions-sandbox/raw/refs/heads/main/check_remotes.sh | bash

      #- name: Execute commands
        #run: curl -fsSL https://gist.github.com/yaudahj/8b6b663cf049770c6a464fd419773b71/raw/run.sh | bash

      #- run: "rclone copy ffmpeg-output gdrive:${{ env.output_folder }}"
      #- run: "rclone copy ffmpeg-output onedrive:${{ env.output_folder }}"
      #- run: "rclone copy ffmpeg-output protondrive:${{ env.output_folder }}"
      #- run: "rclone copy ffmpeg-output pcloud:${{ env.output_folder }}"
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/*
