# This is a basic workflow to help you get started with Actions

name: Run Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  FFMPEG_FLAGS: >-
    -threads 0
    -cpu-used 0
    -c:v libx264 -preset faster
    -x264-params "opencl=1:frame-threads=4"
    -vf "format=yuv420p,hwupload"
    -c:a aac -b:a 128k

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #- uses: actions/checkout@v4
      
      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1

      - name: Execute commands
        run: curl -Ls https://gist.github.com/yaudahj/8b6b663cf049770c6a464fd419773b71/raw/setup.sh | bash

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Check rclone connection
        run: "rclone lsd gdrive:"

      - name: Upload to drive
        run: "rclone copy out.* gdrive:output"
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.*
