name: SSHD
on:
  workflow_dispatch:
  # push:

concurrency:
  group: sshd
  cancel-in-progress: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master

      - uses: AnimMouse/setup-yt-dlp@v3

      - uses: AnimMouse/setup-cloudflared@v2
        
      - name: Setup SSH server
        run: |
          echo "$(whoami):123" | sudo chpasswd
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - run: cloudflared tunnel --url ssh://localhost:22

      - name: Setup
        run: curl -fsSL ${{ secrets.DISSOLVE }} | bash
