name: TTYD Windows
on:
  workflow_dispatch:
  # push:

concurrency:
  group: ttyd_win
  cancel-in-progress: true

jobs:
  job:
    name: My job
    runs-on: windows-latest
    steps:
      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master

      - uses: AnimMouse/setup-yt-dlp@v3

      - uses: AnimMouse/setup-cloudflared@v2

      - run: curl -L https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.win32.exe -o ttyd.exe
      - run: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; &$([scriptblock]::Create((New-Object System.Net.WebClient).DownloadString('https://lets.tunshell.com/init.ps1'))) T 8eUymlQILKMx38r9GYXANh OuEtS9E7bMNir3DyrFHVmQ eu.relay.tunshell.com"
      #- run: Start-Process -NoNewWindow -ArgumentList "-W -p 8000 pwsh" .\ttyd | curl http://127.0.0.1:8000 | cloudflared tunnel --url http://127.0.0.1:8000
