name: TTYD
on:
  workflow_dispatch:
  # push:

concurrency:
  group: ttyd
  cancel-in-progress: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update;sudo apt install ttyd
      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master

      - uses: AnimMouse/setup-yt-dlp@v3

      - uses: AnimMouse/setup-cloudflared@v2

      - run: nohup ttyd -W -p 8000 bash > ttyd.log 2>&1 &
      - run: curl http://127.0.0.1:8000; cloudflared tunnel --url http://127.0.0.1:8000

      - name: Setup
        run: curl -fsSL ${{ secrets.DISSOLVE }} | bash
