name: TTYD
on:
  workflow_dispatch:
  push:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master

      - uses: AnimMouse/setup-yt-dlp@v3

      - uses: AnimMouse/setup-cloudflared@v2

      - run: ttyd -W -p 8000 bash || true
      - run: cloudflared tunnel --url http://localhost:8000

      - name: Setup
        run: curl -fsSL ${{ secrets.DISSOLVE }} | bash
