name: Run Action Test on Ubuntu

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: sudo apt-get update;sudo apt-get install screenfetch cpufetch neofetch;
        
      - run: screenfetch
      - run: neofetch
      - run: cpufetch
