name: Run Action Test on Ubuntu

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update;sudo apt-get install screenfetch cpufetch neofetch;screenfetch neofetch cpufetch;
